<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0;net6.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>lshash</AssemblyName>
    <RootNamespace>LsHash</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
    <RuntimeHostConfigurationOption Include="System.Globalization.PredefinedCulturesOnly" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
    <PackageReference Include="Blake3" Version="2.2.1" Condition="'$(TargetFramework)' != 'net6.0'" />
    <PackageReference Include="Blake3" Version="0.6.1" Condition="'$(TargetFramework)' == 'net6.0'" />
  </ItemGroup>

  <ItemGroup>
    <None Include="vendor/libblake3gpu.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>